### ISSUE TITLE
Checkbox color inheritance

### ISSUE THREAD

**Issue by kimothorick** [mohamed-tayeh/Task-List#1]
Would you kindly make the task item checkbox inherit the text color rather than set it separately? On the other hand, if more customizability options are to be granted to the user, I think an additional slot for the checkbox color can be added in the config file and have it inherit that value.

**Comment by mohamed-tayeh** [comment]
Sounds good. 

I like the idea of having the checkbox have it's own color variables.

I will add two variables to the configs - one for the tick color and one for box color.
