### ISSUE TITLE
Scrolling Bug? after !aclear

### ISSUE THREAD

**Issue by TheAntiqueFox** [mohamed-tayeh/Task-List#17]
Hello again!
I noticed that when I clear a lengthy list, the list continues to try and do the scrolling function, even when the number of tasks doesn't fully fill the page! Could you look into it? 
Thank you moh <3,
Fox

**Comment by mohamed-tayeh** [comment]
@TheAntiqueFox Should be good now! Please feel free to re-open the issue if you ever experience it again (:
