### ISSUE TITLE
taskadel not accepting user arguments

### ISSUE THREAD

**Issue by reddit-sysalex** [mohamed-tayeh/Task-List#6]
I noticed when running this, we can't seem to get `!taskadel` to notice a recipient. At first I thought I was just using the command wrong, however further testing identified that the command doesn't accept any arguments.

For example, we have two accounts, userA a moderator and userB a viewer. userA creates a task, userB also creates a task. Let's say userA now wants to delete userB's task, you would expect to run `!taskadel userB`, however that deletes userA's task rather than userB's task. You run the command again, noticing that userA's task is gone, and the message returned tells you that userA has no tasks.

**Comment by mohamed-tayeh** [comment]
@reddit-sysalex I will look into it right away

Just to double check you are using the latest version of the task list correct?

**Comment by reddit-sysalex** [comment]
@mohamed-tayeh Thanks a lot. Correct, using the latest version.

**Comment by mohamed-tayeh** [comment]
@reddit-sysalex Thank you again for opening the issue and bringing it to my attention, my apologies for any inconvenience that it might have brought to your stream. 

I have tested it several times, it's working well for me. Please let me know how it is on your end.

Also, please don't hesitate to contact me if anything comes up or if you would like a new feature to be added to the task list.
